name: GPT2
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py37he774522_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2020.12.8=haa95532_0
  - certifi=2020.12.5=py37haa95532_0
  - cffi=1.14.4=py37hcd4344a_0
  - chardet=4.0.0=py37haa95532_1003
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=3.3.1=py37hcd4344a_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - icu=58.2=ha925a31_3
  - idna=2.10=py_0
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.19.0=py37hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - jedi=0.18.0=py37haa95532_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.0=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h196d8e1_0
  - mkl_fft=1.2.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - notebook=6.1.6=py37haa95532_0
  - numpy-base=1.19.2=py37ha3acd2a_0
  - openssl=1.1.1i=h2bbff1b_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.3=py37haa95532_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=20.3.3=py37haa95532_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - pycparser=2.20=py_2
  - pygments=2.7.4=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.17.3=py37he774522_0
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.1=py_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyzmq=20.0.0=py37hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - regex=2020.11.13=py37h2bbff1b_0
  - requests=2.25.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=51.1.2=py37haa95532_4
  - sip=4.19.8=py37h6538335_0
  - six=1.15.0=py37haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - terminado=0.9.2=py37haa95532_0
  - testpath=0.4.4=py_0
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.0.5=py_0
  - urllib3=1.26.2=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - absl-py==0.11.0
    - astor==0.8.1
    - blis==0.7.4
    - cached-property==1.5.2
    - catalogue==1.0.0
    - click==7.1.2
    - cycler==0.10.0
    - cymem==2.0.5
    - en-core-web-sm==2.3.1
    - fire==0.3.1
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - importlib-metadata==3.4.0
    - joblib==1.0.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - matplotlib==3.3.4
    - munkres==1.1.4
    - murmurhash==1.0.5
    - networkx==2.3
    - nltk==3.5
    - numpy==1.19.5
    - opt-einsum==3.3.0
    - pandas==1.2.0
    - pillow==8.1.0
    - plac==1.1.3
    - preshed==3.0.5
    - protobuf==3.14.0
    - pytz==2020.5
    - scikit-learn==0.21.3
    - scipy==1.6.0
    - seaborn==0.11.1
    - snorkel==0.9.6
    - spacy==2.3.5
    - srsly==1.0.5
    - tensorboard==1.15.0
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - thinc==7.4.5
    - torch==1.7.1
    - tqdm==4.56.0
    - typing-extensions==3.7.4.3
    - wasabi==0.8.1
    - werkzeug==1.0.1
prefix: C:\Users\sefilipi\AppData\Local\Continuum\anaconda3\envs\GPT2
